export default {
  globals: { "ts-jest": { tsconfig: "tsconfig.json" } },
  moduleFileExtensions: ["js", "json", "ts"],
  moduleDirectories: ["node_modules"],
  rootDir: "",
  setupFiles: ["dotenv/config"],
  setupFilesAfterEnv: ["./test/jest.setup.ts"],
  testRegex: ".*?(?=\\.spec).*?\\.ts",
  testPathIgnorePatterns: ["/node_modules/", ".*\\.e2e.test\\.ts", "/dist/"],
  transform: {
    ".+\\.ts$": "ts-jest",
  },
  collectCoverage: false,
  collectCoverageFrom: [
    "*.ts",
    "**/*.ts",
    "!index.ts",
    "!src/app.ts",
    "!src/server.ts",
    "!**/config.ts",
    "!**/generated/*",
    "!**/middleware/**/*.ts",
    "!**/*.config.ts",
    "!**/*.enum.ts",
    "!**/*.module.ts",
    "!**/*.dto.ts",
    "!**/*.spec.ts",
    "!**/*.controller.ts",
    "!**/*.interface.ts",
    "!**/*.interfaces.ts",
    "!**/*.mocks.ts",
    "!**/*.mapper.table.ts",
    "!**/models/**",
    "!**/exports.ts",
  ],
  coverageDirectory: "../test/coverage",
  coverageThreshold: {
    global: {
      functions: 90,
      lines: 90,
    },
  },
};
